### PR TITLE
Update deps, and add linter

### PR DESCRIPTION
**Pull request by JereMiO**
### Description

Update minor version of deps 
Add linter, configure, and fix files

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [X] Other

### CODE REVIEW

**Comment by naeruru** [comment]
it seems that a later version of vite-plugin-electron change(?) the use of nodeIntegration, which breaks the use of imports (such as fs). I have to look into this because it currently makes this PR not useable due to this package update. everything else seems to check out though

**Comment by JereMiO** [comment]
For this dep issue, we should check vite configuration and the way to define new Worker into Footer.vue

**Comment by naeruru** [comment]
sounds good. I will let that be in another issue/pr/commit. this one looks good and I will merge soon. thanks for your work!!

**Comment by naeruru** [comment]
Actually, I just noticed it's very unhappy about the `Property ... does not exist on type '{}'` for all js inserts in any `<template>` tag. A little late though.. since I merged. But if you could take a look at that, I would appreciate it.

**Pull request merged**
